{#
Copyright (c) 2023-present Snowplow Analytics Ltd. All rights reserved.
This program is licensed to you under the Snowplow Personal and Academic License Version 1.0,
and you may not use this file except in compliance with the Snowplow Personal and Academic License Version 1.0.
You may obtain a copy of the Snowplow Personal and Academic License Version 1.0 at https://docs.snowplow.io/personal-and-academic-license-1.0/
#}

{# CWV tests run on a different source dataset, this is an easy way to hack them together. #}
{% if not var("snowplow__enable_cwv", false) and not var("snowplow__enable_screen_summary_context", false) %}

  -- page view context is given as json string in csv. Parse json
  with prep as (
    select
      *,
      json(contexts_com_snowplowanalytics_snowplow_web_page_1_0_0) as contexts_com_snowplowanalytics_snowplow_web_page_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_cmp_visible_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_cmp_visible_1,
      json(contexts_com_iab_snowplow_spiders_and_robots_1_0_0) as contexts_com_iab_snowplow_spiders_and_robots_1,
      json(contexts_com_snowplowanalytics_snowplow_ua_parser_context_1_0_0) as contexts_com_snowplowanalytics_snowplow_ua_parser_context_1,
      json(contexts_nl_basjes_yauaa_context_1_0_0) as contexts_nl_basjes_yauaa_context_1,
      json(unstruct_event_com_snowplowanalytics_mobile_screen_view_1_0_0) as unstruct_event_com_snowplowanalytics_mobile_screen_view_1,
      json(contexts_com_snowplowanalytics_snowplow_client_session_1_0_0) as contexts_com_snowplowanalytics_snowplow_client_session_1,
      json(contexts_com_snowplowanalytics_snowplow_geolocation_context_1_0_0) as contexts_com_snowplowanalytics_snowplow_geolocation_context_1,
      json(contexts_com_snowplowanalytics_mobile_application_1_0_0) as contexts_com_snowplowanalytics_mobile_application_1,
      json(contexts_com_snowplowanalytics_mobile_deep_link_1_0_0) as contexts_com_snowplowanalytics_mobile_deep_link_1,
      json(contexts_com_snowplowanalytics_snowplow_browser_context_1_0_0) as contexts_com_snowplowanalytics_snowplow_browser_context_1,
      json(contexts_com_snowplowanalytics_snowplow_mobile_context_1_0_0) as contexts_com_snowplowanalytics_snowplow_mobile_context_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_application_error_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_application_error_1,
      json(contexts_com_snowplowanalytics_mobile_screen_1_0_0) as contexts_com_snowplowanalytics_mobile_screen_1

    from {{ ref('snowplow_unified_events') }}
    )

  , flatten as (
    select
      *,
      contexts_nl_basjes_yauaa_context_1->0->>'agentClass' as agent_class,
      contexts_nl_basjes_yauaa_context_1->0->>'agentInformationEmail' as agent_information_email,
      contexts_nl_basjes_yauaa_context_1->0->>'agentName' as agent_name,
      contexts_nl_basjes_yauaa_context_1->0->>'agentNameVersion' as agent_name_version,
      contexts_nl_basjes_yauaa_context_1->0->>'agentNameVersionMajor' as agent_name_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'agentVersion' as agent_version,
      contexts_nl_basjes_yauaa_context_1->0->>'agentVersionMajor' as agent_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceBrand' as device_brand,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceClass' as device_class,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceCpu' as device_cpu,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceCpuBits' as device_cpu_bits,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceName' as device_name,
      contexts_nl_basjes_yauaa_context_1->0->>'deviceVersion' as device_version,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineClass' as layout_engine_class,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineName' as layout_engine_name,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineNameVersion' as layout_engine_name_version,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineNameVersionMajor' as layout_engine_name_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineVersion' as layout_engine_version,
      contexts_nl_basjes_yauaa_context_1->0->>'layoutEngineVersionMajor' as layout_engine_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'networkType' as network_type,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemClass' as operating_system_class,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemName' as operating_system_name,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemNameVersion' as operating_system_name_version,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemNameVersionMajor' as operating_system_name_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemVersion' as operating_system_version,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemVersionBuild' as operating_system_version_build,
      contexts_nl_basjes_yauaa_context_1->0->>'operatingSystemVersionMajor' as operating_system_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'webviewAppName' as webview_app_name,
      contexts_nl_basjes_yauaa_context_1->0->>'webviewAppNameVersionMajor' as webview_app_name_version_major,
      contexts_nl_basjes_yauaa_context_1->0->>'webviewAppVersion' as webview_app_version,
      contexts_nl_basjes_yauaa_context_1->0->>'webviewAppVersionMajor' as webview_app_version_major,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'category' as category,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'primaryImpact' as primaryImpact,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'reason' as reason,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'spiderOrRobot' as spiderOrRobot,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'basis_for_processing' as basisForProcessing,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'consent_scopes' as consentScopes,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'consent_url' as consentUrl,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'consent_version' as consentVersion,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'domains_applied' as domainsApplied,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'event_type' as eventType,
      unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1->0->>'gdpr_applies' as gdprApplies,
      unstruct_event_com_snowplowanalytics_snowplow_cmp_visible_1->0->>'elapsed_time' as elapsedTime,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'id' AS varchar) AS id,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'name' AS varchar) AS name,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'previousId' AS varchar) AS previousId,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'previousName' AS varchar) AS previousName,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'previousType' AS varchar) AS previousType,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'transitionType' AS varchar) AS transitionType,
      CAST(unstruct_event_com_snowplowanalytics_mobile_screen_view_1->0->>'type' AS varchar) AS type,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'firstEventId' AS varchar) AS firstEventId,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'previousSessionId' AS varchar) AS previousSessionId,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'sessionId' AS varchar) AS sessionId,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'sessionIndex' AS int) AS sessionIndex,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'userId' AS varchar) AS userId,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'eventIndex' AS int) AS eventIndex,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'storageMechanism' AS varchar) AS storageMechanism,
      CAST(contexts_com_snowplowanalytics_snowplow_client_session_1->0->>'firstEventTimestamp' AS timestamp) AS firstEventTimestamp,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'latitude' AS float) AS latitude,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'longitude' AS float) AS longitude,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'latitudeLongitudeAccuracy' AS float) AS latitudeLongitudeAccuracy,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'altitude' AS float) AS altitude,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'altitudeAccuracy' AS float) AS altitudeAccuracy,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'bearing' AS float) AS bearing,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'speed' AS float) AS speed,
      CAST(contexts_com_snowplowanalytics_snowplow_geolocation_context_1->0->>'timestamp' AS int) AS timestamp,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'viewport' AS varchar) AS viewport,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'documentSize' AS varchar) AS documentSize,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'resolution' AS varchar) AS resolution,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'colorDepth' AS int) AS colorDepth,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'devicePixelRatio' AS float) AS devicePixelRatio,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'cookiesEnabled' AS boolean) AS cookiesEnabled,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'online' AS boolean) AS online,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'browserLanguage' AS varchar) AS browserLanguage,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'documentLanguage' AS varchar) AS documentLanguage,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'webdriver' AS boolean) AS webdriver,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'deviceMemory' AS bigint) AS deviceMemory,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'hardwareConcurrency' AS int) AS hardwareConcurrency,
      CAST(contexts_com_snowplowanalytics_snowplow_browser_context_1->0->>'tabId' AS varchar) AS tabId,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'deviceManufacturer' AS varchar) AS deviceManufacturer,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'deviceModel' AS varchar) AS deviceModel,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'osType' AS varchar) AS osType,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'osVersion' AS varchar) AS osVersion,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'androidIdfa' AS varchar) AS androidIdfa,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'appleIdfa' AS varchar) AS appleIdfa,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'appleIdfv' AS varchar) AS appleIdfv,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'carrier' AS varchar) AS carrier,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'openIdfa' AS varchar) AS openIdfa,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'networkTechnology' AS varchar) AS networkTechnology,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'networkType' AS varchar(255)) AS networkType,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'physicalMemory' AS bigint) AS physicalMemory,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'systemAvailableMemory' AS bigint) AS systemAvailableMemory,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'appAvailableMemory' AS bigint) AS appAvailableMemory,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'batteryLevel' AS int) AS batteryLevel,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'batteryState' AS string) AS batteryState,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'lowPowerMode' AS string) AS lowPowerMode,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'availableStorage' AS bigint) AS availableStorage,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'totalStorage' AS bigint) AS totalStorage,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'isPortrait' AS boolean) AS isPortrait,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'resolution' AS string) AS resolution2,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'scale' AS string) AS scale,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'language' AS string) AS language,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'appSetId' AS string) AS appSetId,
      CAST(contexts_com_snowplowanalytics_snowplow_mobile_context_1->0->>'appSetIdScope' AS string) AS appSetIdScope,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'id' AS varchar) AS id2,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'name' AS varchar) AS name2,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'activity' AS varchar) AS activity,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'fragment' AS varchar) AS fragment,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'topViewController' AS varchar) AS topViewController,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'type' AS varchar) AS type2,
      CAST(contexts_com_snowplowanalytics_mobile_screen_1->0->>'viewController' AS varchar(255)) AS viewController,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'message' AS varchar) AS message,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'programmingLanguage' AS varchar) AS programmingLanguage,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'className' AS varchar) AS className,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'exceptionName' AS varchar) AS exceptionName,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'isFatal' AS boolean) AS isFatal,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'lineNumber' AS float) AS lineNumber,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'stackTrace' AS varchar) AS stackTrace,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'threadId' AS int) AS threadId,
      CAST(unstruct_event_com_snowplowanalytics_snowplow_application_error_1->0->>'threadName' AS varchar) AS threadName

    from prep

  )

  select
    app_id,
    platform,
    etl_tstamp,
    collector_tstamp,
    dvce_created_tstamp,
    event,
    event_id,
    txn_id,
    name_tracker,
    v_tracker,
    v_collector,
    v_etl,
    user_id,
    user_ipaddress,
    user_fingerprint,
    domain_userid,
    domain_sessionidx,
    network_userid,
    geo_country,
    geo_region,
    geo_city,
    geo_zipcode,
    geo_latitude,
    geo_longitude,
    geo_region_name,
    ip_isp,
    ip_organization,
    ip_domain,
    ip_netspeed,
    page_url,
    page_title,
    page_referrer,
    page_urlscheme,
    page_urlhost,
    page_urlport,
    page_urlpath,
    page_urlquery,
    page_urlfragment,
    refr_urlscheme,
    refr_urlhost,
    refr_urlport,
    refr_urlpath,
    refr_urlquery,
    refr_urlfragment,
    refr_medium,
    refr_source,
    refr_term,
    mkt_medium,
    mkt_source,
    mkt_term,
    mkt_content,
    mkt_campaign,
    se_category,
    se_action,
    se_label,
    se_property,
    se_value,
    tr_orderid,
    tr_affiliation,
    tr_total,
    tr_tax,
    tr_shipping,
    tr_city,
    tr_state,
    tr_country,
    ti_orderid,
    ti_sku,
    ti_name,
    ti_category,
    ti_price,
    ti_quantity,
    pp_xoffset_min,
    pp_xoffset_max,
    pp_yoffset_min,
    pp_yoffset_max,
    useragent,
    br_name,
    br_family,
    br_version,
    br_type,
    br_renderengine,
    br_lang,
    br_features_pdf,
    br_features_flash,
    br_features_java,
    br_features_director,
    br_features_quicktime,
    br_features_realplayer,
    br_features_windowsmedia,
    br_features_gears,
    br_features_silverlight,
    br_cookies,
    br_colordepth,
    br_viewwidth,
    br_viewheight,
    os_name,
    os_family,
    os_manufacturer,
    os_timezone,
    dvce_type,
    dvce_ismobile,
    dvce_screenwidth,
    dvce_screenheight,
    doc_charset,
    doc_width,
    doc_height,
    tr_currency,
    tr_total_base,
    tr_tax_base,
    tr_shipping_base,
    ti_currency,
    ti_price_base,
    base_currency,
    geo_timezone,
    mkt_clickid,
    mkt_network,
    etl_tags,
    dvce_sent_tstamp,
    refr_domain_userid,
    refr_dvce_tstamp,
    domain_sessionid,
    derived_tstamp,
    event_vendor,
    event_name,
    event_format,
    event_version,
    event_fingerprint,
    true_tstamp,
    load_tstamp,
    contexts_com_snowplowanalytics_snowplow_web_page_1,
    json_object('basisForProcessing', basisForProcessing,'consentScopes', consentScopes, 'consentUrl', consentUrl, 'consentVersion', consentVersion, 'domainsApplied', domainsApplied, 'eventType', eventType, 'gdprApplies', gdprApplies) as unstruct_event_com_snowplowanalytics_snowplow_consent_preferences_1,
    json_object('elapsedTime', elapsedTime) as unstruct_event_com_snowplowanalytics_snowplow_cmp_visible_1,
    contexts_com_iab_snowplow_spiders_and_robots_1,
    contexts_com_snowplowanalytics_snowplow_ua_parser_context_1,
    contexts_nl_basjes_yauaa_context_1,
    json_object('id',id,'name',name,'previousId',previousId,'previousName',previousName,'previousType',previousType,'transitionType',transitionType,'type',type) as unstruct_event_com_snowplowanalytics_mobile_screen_view_1,
    json('[{"sessionId":"'||sessionId||'","userId":"'||userId||'", "sessionIndex":"'||sessionIndex||'", "firstEventId":"'||firstEventId||'", "previousSessionId":"'||previousSessionId||'", "eventIndex":"'||eventIndex||'", "storageMechanism":"'||storageMechanism||'", "firstEventTimestamp":"'||firstEventTimestamp||'"}]' ) as contexts_com_snowplowanalytics_snowplow_client_session_1,
    json([json_object('latitude', latitude, 'longitude', longitude, 'latitudeLongitudeAccuracy', latitudeLongitudeAccuracy, 'altitude', altitude, 'altitudeAccuracy', altitudeAccuracy, 'bearing', bearing,'speed', speed,'timestamp', timestamp)]) as contexts_com_snowplowanalytics_snowplow_geolocation_context_1,
    contexts_com_snowplowanalytics_mobile_application_1,
    contexts_com_snowplowanalytics_mobile_deep_link_1,
    json('[{"viewport":"'||viewport||'", "documentSize":"'||documentSize||'", "resolution":"'||resolution||'", "colorDepth":"'||colorDepth||'", "devicePixelRatio":"'||devicePixelRatio||'", "cookiesEnabled":"'||cookiesEnabled||'", "online":"'||online||'", "browserLanguage":"'||browserLanguage||'","documentLanguage":"'||documentLanguage||'", "webdriver":"'||webdriver||'", "deviceMemory":"'||deviceMemory||'", "hardwareConcurrency":"'||hardwareConcurrency||'", "tabId":"'||tabId||'"}]' ) as contexts_com_snowplowanalytics_snowplow_browser_context_1,
    json('[{"viewport":"'||viewport||'", "documentSize":"'||documentSize||'", "resolution":"'||resolution||'", "colorDepth":"'||colorDepth||'", "devicePixelRatio":"'||devicePixelRatio||'", "cookiesEnabled":"'||cookiesEnabled||'", "online":"'||online||'", "browserLanguage":"'||browserLanguage||'","documentLanguage":"'||documentLanguage||'", "webdriver":"'||webdriver||'", "deviceMemory":"'||deviceMemory||'", "hardwareConcurrency":"'||hardwareConcurrency||'", "tabId":"'||tabId||'"}]' ) as contexts_com_snowplowanalytics_snowplow_browser_context_2,
    json('[{"deviceManufacturer":"'||deviceManufacturer||'", "deviceModel":"'||deviceModel||'", "osType":"'||osType||'", "osVersion":"'||osVersion||'", "androidIdfa":"'||androidIdfa||'", "appleIdfa":"'||appleIdfa||'", "appleIdfv":"'||appleIdfv||'", "carrier":"'||carrier||'", "openIdfa":"'||openIdfa||'", "networkTechnology":"'||networkTechnology||'", "networkType":"'||networkType||'", "physicalMemory":"'||physicalMemory||'", "systemAvailableMemory":"'||systemAvailableMemory||'", "appAvailableMemory":"'||appAvailableMemory||'", "batteryLevel":"'||batteryLevel||'", "batteryState":"'||batteryState||'", "lowPowerMode":"'||lowPowerMode||'", "availableStorage":"'||availableStorage||'", "isPortrait":"'||isPortrait||'", "totalStorage":"'||totalStorage||'", "resolution":"'||resolution2||'", "scale":"'||scale||'", "language":"'||language||'", "appSetId":"'||appSetId||'", "appSetIdScope":"'||appSetIdScope||'"}]' ) as contexts_com_snowplowanalytics_snowplow_mobile_context_1,
    json('[{"id":"'||id2||'", "name":"'||name2||'", "activity":"'||activity||'", "fragment":"'||fragment||'", "topViewController":"'||topViewController||'", "type":"'||type2||'", "viewController":"'||viewController||'"}]' ) as contexts_com_snowplowanalytics_mobile_screen_1,
    json_object('message', message,'programmingLanguage', programmingLanguage, 'className', className, 'exceptionName', exceptionName, 'isFatal', isFatal, 'lineNumber', lineNumber, 'stackTrace', stackTrace, 'threadId', threadId, 'threadName', threadName) as unstruct_event_com_snowplowanalytics_snowplow_application_error_1

  from flatten

{% elif var("snowplow__enable_screen_summary_context", false) %}

    select
      *,

      json(unstruct_event_com_snowplowanalytics_mobile_screen_view_1_0_0) as unstruct_event_com_snowplowanalytics_mobile_screen_view_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_application_background_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_application_background_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_application_foreground_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_application_foreground_1,
      json(contexts_com_snowplowanalytics_snowplow_client_session_1_0_2) as contexts_com_snowplowanalytics_snowplow_client_session_1,
      json(contexts_com_snowplowanalytics_mobile_application_lifecycle_1_0_0) as contexts_com_snowplowanalytics_mobile_application_lifecycle_1,
      json(contexts_com_snowplowanalytics_snowplow_mobile_context_1_0_3) as contexts_com_snowplowanalytics_snowplow_mobile_context_1,
      json(contexts_com_snowplowanalytics_mobile_application_1_0_0) as contexts_com_snowplowanalytics_mobile_application_1,
      json(contexts_com_snowplowanalytics_mobile_screen_1_0_0) as contexts_com_snowplowanalytics_mobile_screen_1,
      json(contexts_com_snowplowanalytics_mobile_screen_summary_1_0_0) as contexts_com_snowplowanalytics_mobile_screen_summary_1,
      json(contexts_com_snowplowanalytics_iglu_anything_a_1_0_0) as contexts_com_snowplowanalytics_iglu_anything_a_1,
      json(contexts_com_snowplowanalytics_snowplow_ecommerce_user_1_0_0) as contexts_com_snowplowanalytics_snowplow_ecommerce_user_1,
      json(contexts_com_snowplowanalytics_snowplow_gdpr_1_0_0) as contexts_com_snowplowanalytics_snowplow_gdpr_1

    from {{ ref('snowplow_unified_screen_engagement_events') }}

{% else %}

  -- page view context is given as json string in csv. Parse json

    with prep as (
      select
      *,
      json(contexts_com_snowplowanalytics_snowplow_web_page_1_0_0) as contexts_com_snowplowanalytics_snowplow_web_page_1,
      json(unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1_0_0) as unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1,
      json(contexts_nl_basjes_yauaa_context_1_0_0) as contexts_nl_basjes_yauaa_context_1,
      json(contexts_com_iab_snowplow_spiders_and_robots_1_0_0) as contexts_com_iab_snowplow_spiders_and_robots_1
    from {{ ref('snowplow_unified_web_vital_events') }}

    )

    , flatten as (
    select
      *,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'lcp' as lcp,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'fcp' as fcp,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'fid' as fid,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'cls' as cls,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'inp' as inp,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'ttfb' as ttfb,
      unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1->0->>'navigation_type' as navigationType,
      contexts_nl_basjes_yauaa_context_1->0->>'device_class' as deviceClass,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_class' as agentClass,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_name' as agentName,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_name_version' as agentNameVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_name_version_major' as agentNameVersionMajor,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_version' as agentVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'agent_version_major' as agentVersionMajor,
      contexts_nl_basjes_yauaa_context_1->0->>'device_brand' as deviceBrand,
      contexts_nl_basjes_yauaa_context_1->0->>'device_name' as deviceName,
      contexts_nl_basjes_yauaa_context_1->0->>'device_version' as deviceVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_class' as layoutEngineClass,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_name' as layoutEngineName,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_name_version' as layoutEngineNameVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_name_version_major' as layoutEngineNameVersionMajor,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_version' as layoutEngineVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'layout_engine_version_major' as layoutEngineVersionMajor,
      contexts_nl_basjes_yauaa_context_1->0->>'operating_system_class' as operatingSystemClass,
      contexts_nl_basjes_yauaa_context_1->0->>'operating_system_name' as operatingSystemName,
      contexts_nl_basjes_yauaa_context_1->0->>'operating_system_name_version' as operatingSystemNameVersion,
      contexts_nl_basjes_yauaa_context_1->0->>'operating_system_version' as operatingSystemVersion,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'category' as category,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'primary_impact' as primaryImpact,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'reason' as reason,
      contexts_com_iab_snowplow_spiders_and_robots_1->0->>'spider_or_robot' as spiderOrRobot

    from prep

  )

  select
    app_id,
    platform,
    etl_tstamp,
    collector_tstamp,
    dvce_created_tstamp,
    event,
    event_id,
    txn_id,
    name_tracker,
    v_tracker,
    v_collector,
    v_etl,
    user_id,
    user_ipaddress,
    user_fingerprint,
    domain_userid,
    domain_sessionidx,
    network_userid,
    geo_country,
    geo_region,
    geo_city,
    geo_zipcode,
    geo_latitude,
    geo_longitude,
    geo_region_name,
    ip_isp,
    ip_organization,
    ip_domain,
    ip_netspeed,
    page_url,
    page_title,
    page_referrer,
    page_urlscheme,
    page_urlhost,
    page_urlport,
    page_urlpath,
    page_urlquery,
    page_urlfragment,
    refr_urlscheme,
    refr_urlhost,
    refr_urlport,
    refr_urlpath,
    refr_urlquery,
    refr_urlfragment,
    refr_medium,
    refr_source,
    refr_term,
    mkt_medium,
    mkt_source,
    mkt_term,
    mkt_content,
    mkt_campaign,
    se_category,
    se_action,
    se_label,
    se_property,
    se_value,
    tr_orderid,
    tr_affiliation,
    tr_total,
    tr_tax,
    tr_shipping,
    tr_city,
    tr_state,
    tr_country,
    ti_orderid,
    ti_sku,
    ti_name,
    ti_category,
    ti_price,
    ti_quantity,
    pp_xoffset_min,
    pp_xoffset_max,
    pp_yoffset_min,
    pp_yoffset_max,
    useragent,
    br_name,
    br_family,
    br_version,
    br_type,
    br_renderengine,
    br_lang,
    br_features_pdf,
    br_features_flash,
    br_features_java,
    br_features_director,
    br_features_quicktime,
    br_features_realplayer,
    br_features_windowsmedia,
    br_features_gears,
    br_features_silverlight,
    br_cookies,
    br_colordepth,
    br_viewwidth,
    br_viewheight,
    os_name,
    os_family,
    os_manufacturer,
    os_timezone,
    dvce_type,
    dvce_ismobile,
    dvce_screenwidth,
    dvce_screenheight,
    doc_charset,
    doc_width,
    doc_height,
    tr_currency,
    tr_total_base,
    tr_tax_base,
    tr_shipping_base,
    ti_currency,
    ti_price_base,
    base_currency,
    geo_timezone,
    mkt_clickid,
    mkt_network,
    etl_tags,
    dvce_sent_tstamp,
    refr_domain_userid,
    refr_dvce_tstamp,
    domain_sessionid,
    derived_tstamp,
    event_vendor,
    event_name,
    event_format,
    event_version,
    event_fingerprint,
    true_tstamp,
    load_tstamp,
    contexts_com_snowplowanalytics_snowplow_web_page_1,
    json_object('cls', cls, 'fcp', fcp, 'fid', fid, 'inp', inp, 'lcp', lcp, 'navigationType', navigationType, 'ttfb', ttfb) as unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1,
    json('[{"deviceClass":"'||deviceClass||'", "agentClass":"'||agentClass||'", "agentName":"'||agentName||'", "agentNameVersion":"'||agentNameVersion||'", "agentNameVersionMajor":"'||agentNameVersionMajor||'", "agentVersion":"'||agentVersion||'", "agentVersionMajor":"'||agentVersionMajor||'", "deviceBrand":"'||deviceBrand||'", "deviceName":"'||deviceName||'", "deviceVersion":"'||deviceVersion||'", "layoutEngineClass":"'||layoutEngineClass||'", "layoutEngineName":"'||layoutEngineName||'", "layoutEngineNameVersion":"'||layoutEngineNameVersion||'", "layoutEngineNameVersionMajor":"'||layoutEngineNameVersionMajor||'", "layoutEngineVersion":"'||layoutEngineVersion||'", "layoutEngineVersionMajor":"'||layoutEngineVersionMajor||'", "operatingSystemClass":"'||operatingSystemClass||'", "operatingSystemName":"'||operatingSystemName||'", "operatingSystemNameVersion":"'||operatingSystemNameVersion||'", "operatingSystemVersion":"'||operatingSystemVersion||'"}]') as contexts_nl_basjes_yauaa_context_1,
    json('[{"category":"'||category||'", "primaryImpact":"'||primaryImpact||'", "reason":"'||reason||'", "spiderOrRobot":"'||spiderOrRobot||'"}]') as contexts_com_iab_snowplow_spiders_and_robots_1

from flatten

{% endif %}
