name: 'snowplow_custom_example'
version: '0.15.2'
config-version: 2

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  snowplow__sessions_table: "{{ ref('snowplow_unified_sessions_custom') }}" # Redirect references to sessions table to your custom version.

models:
  snowplow_custom_example:
    snowplow_unified_custom_modules:
      +tags: snowplow_unified_incremental #Adds tag to all models in the 'snowplow_unified_custom_modules' directory
  snowplow_unified: # Only applies to models provided by the Snowplow Web dbt package
    sessions:
      snowplow_unified_sessions:
        +enabled: false # Disable the snowplow_unified_sessions model as we have our custom version, snowplow_unified_sessions_custom
